@startuml spa-rendering

!include theme/core.puml
GREY_ARROW

hide footbox

actor user
participant "Agent\nBrowser/App" as B
participant "UI Host\nWeb Server" as U
participant "API Host\nWeb Server" as A
participant "CDN\n" as C 

title client-side rendering
user -> B: access SPA
autonumber "(0)"
B -> U: load
activate U
U --> B: return index html
deactivate U
B -> C: download bundle js and assets
B -> A: get Profile
activate A
A --> B: return
deactivate A
B -> C: download other assets

loop render page
    B -> A: get other info
    activate A
    A --> B: return
    deactivate A
    B -> B: render page
end

newpage server-side rendering
autonumber stop

user -> B: access SPA
autonumber 1 "(0)"
B -> U: load
activate U
U -> A: get Profile/Settings
activate A
A --> U: return
deactivate A
U --> B: return index html
deactivate U
B -> C: download bundle js and assets

loop render page
    B -> A: get other info
    activate A
    A --> B: return
    deactivate A
    B -> B: render page
end

right footer created by hdouhua 2022-09-23
' %date("yyyy-MM-dd")
@enduml