@startuml restaurant

' !theme cerulean
' !theme bluegray
' or use remote url
' !include https://raw.githubusercontent.com/plantuml/plantuml/master/themes/puml-theme-cerulean-outline.puml
!theme amiga from https://raw.githubusercontent.com/plantuml/plantuml/master/themes
' !include theme/core.puml

left to right direction

actor Guest as g
package Professional {
  actor Chef as c
  actor "Food Critic" as fc
}
package Restaurant {
  usecase "Eat Food" as UC1
  usecase "Pay for Food" as UC2
  usecase "Drink" as UC3
  usecase "Review" as UC4
}

fc --> UC4
g --> UC1
g --> UC2
g --> UC3

@enduml
